/*
 * grunt-shrinkpack
 * https://github.com/jeremyhofman/grunt-shrinkpack
 *
 * Copyright (c) 2016 Jeremy Hofman
 * Licensed under the MIT license.
 */

'use strict';

var shelljs = require('shelljs');

module.exports = function(grunt) {

  // Please see the Grunt documentation for more information regarding task
  // creation: http://gruntjs.com/creating-tasks

  grunt.registerTask('shrinkpack', 'Provides a task for Shrinkpack to run. Requires grunt-shrinkwrap to run before grunt-shrinkpack, as Shrinkpack uses the json file generated by Shrinkwrap.', function() {
    shelljs.exec('shrinkpack .');
  });

};
